eks-s3-seldon-mlflow/README.md, eks-s3-seldon-mlflow/eks.tf, eks-s3-seldon-mlflow/locals.tf, eks-s3-seldon-mlflow/mlflow.tf, eks-s3-seldon-mlflow/outputs.tf, eks-s3-seldon-mlflow/rds.tf, eks-s3-seldon-mlflow/terraform.tf, eks-s3-seldon-mlflow/variables.tf, eks-s3-seldon-mlflow/vpc.tf
I have added the MySQL metadata store on AWS as a stack component. Corresponding documentation change also done.
=> Add AWS RDS metadata store

azureml-minimal/README.md
Hi, I recently tried out the azureml-minimal recipe and found it very useful! Thanks for creating it! Suggesting minor changes to improve the documentation based on the errors that I faced while running the recipe. Hope this is fine.
Let me know in case you'd like me to fix anything.
=> Documentation fixes for AzureML minimal recipe

gcp-vertexai/output_file.tf
=> Remove labels from Vertex configuration

gcp-vertexai/outputs.tf
=> [BUGFIX] Fix mlflow reference when disabled in Vertex recipe

gcp-airflow/metadata.yaml, gcp-kubeflow-kserve/metadata.yaml, gcp-minimal/metadata.yaml, gcp-modular/metadata.yaml, gcp-vertexai/metadata.yaml
=> add gcloud auth requirement to prerequisites

aws-modular/helm.tf, aws-modular/kubernetes.tf, gcp-modular/gke.tf, gcp-modular/helm.tf, gcp-modular/kubernetes.tf, gcp-modular/locals.tf, gcp-modular/vpc.tf
I added the following:
- null checks for the data source that fetches the cluster information for both AWS and GCP
- Fixed the dependency on the cluster for the data source, in the case of GCP.
- Fixed the naming of the vpc to not have unknown values at the time of creation.
=> Fix Kubernetes provider config (check null and fix dependency)

gcp-modular/gke.tf
Reverts zenml-io/mlops-stacks#49
=> Revert "Test branch protection rule"

README.md, aws-kubeflow-kserve/README.md, aws-minimal/README.md, aws-modular/README.md, aws-stores-minimal/README.md, azure-minimal/README.md, azureml-minimal/README.md, gcp-airflow/README.md, gcp-kubeflow-kserve/README.md, gcp-minimal/README.md, gcp-modular/README.md, gcp-vertexai/README.md, k3d-modular/README.md
I have fixed the link to our docs after the major docs update.
=> Fixing the links after the major docs rehab

aws-modular/eks.tf, aws-modular/mlflow.tf
* The ACL issue with S3 creation is fixed
* The k8s service acccount in mlflow namespace should be able to assume the node role to access the S3 bucket now.
=> Fix S3 creation and access from MLflow

scripts/publish.sh
Small fix following token assignment at org-level.
=> Update variable name for release publication token

.gitignore, docs/book/reference/analytics.md, src/mlstacks/analytics/client.py, src/mlstacks/constants.py, src/mlstacks/utils/environment_utils.py
- I have renamed the environment variable from "MLSTACKS_ANALYTICS_OPT_OUT" to "MLSTACKS_ANALYTICS_OPT_IN" and made the necessary adjustments.
=> Renaming the environment variable for analytics

docs/book/reference/zenml.md
Command was too closely tied to testing scenarios. Updated to be more generic.
=> Update zenml-mlstacks sample command

src/mlstacks/enums.py
Referenced in https://github.com/zenml-io/zenml/issues/1812 and fixed here.
=> Add missing Vertex flavor

.github/pull_request_template.md, CONTRIBUTING.md
Copied mostly from https://github.com/zenml-io/zenml/pull/1801
=> Update PR template to discourage PRs on `main`

pyproject.toml
I implemented/fixed _ to achieve _.
accordingly.
change)
=> Bump `mypy`, `ruff` and `black`

pyproject.toml, src/mlstacks/cli/cli.py, src/mlstacks/utils/terraform_utils.py
Enum included as a literal object vs just the actual string value was preventing stack deployment.
accordingly.
change)
=> Fix stack provider value bug

src/mlstacks/terraform/aws-modular/output_file.tf, src/mlstacks/terraform/gcp-modular/output_file.tf
We'd previously enabled Skypilot in #99 but the stack output recipe was using old / incorrect flavor names. These are fixed in this PR.
accordingly.
change)
=> Fix Skypilot output flavor names

src/mlstacks/terraform/aws-modular/values.tfvars.json, src/mlstacks/terraform/aws-modular/variables.tf, src/mlstacks/terraform/gcp-modular/values.tfvars.json, src/mlstacks/terraform/gcp-modular/variables.tf, src/mlstacks/terraform/k3d-modular/values.tfvars.json, src/mlstacks/terraform/k3d-modular/variables.tf
I implemented/fixed _ to achieve _.
accordingly.
change)
=> Bump default zenml versions on TF recipes

.coderabbit.yaml, .gitignore
CodeRabbit reviews set to manual (i.e. user must trigger them manually instead of having them run automatically). Some other basic config settings specified.
accordingly.
change)
=> Add Coderabbit yaml config

docs/book/getting-started/installation.md
This pull request updates the installation.md file to include additional requirements and dependencies for using MLStacks. The changes include adding instructions for installing `jq` as mentioned in #126.
=> Add `jq` as named dependency in documentation
